### ISSUE TITLE
Contains two modules with the same name

### ISSUE THREAD

**Issue by wotnak** [symbioquine/farmOS_land_drawing_tool#1]
![image](https://user-images.githubusercontent.com/52507690/221783433-2348e503-22b9-4701-9684-fe993638eb58.png)

When trying to install this module in the drupal admin ui two modules with the same name are displayed, this can be a bit confusing. It looks like on the `release` branch there are some leftovers from the template repo used to generate this one that should be removed:
```
farmos_vue_demo_page.info.yml
farmos_vue_demo_page.libraries.yml
farmos_vue_demo_page.routing.yml
farmos_vue_demo_page.routing.yml
js/farmos_vue_demo_page.js
js/farmos_vue_demo_page.js.LICENSE.txt
src/Controller/FarmVueDemoPageController.php
```

**Comment by symbioquine** [comment]
Thanks! This should be fixed in a new v1.0.5 release shortly...
